In [12]:
#October 15, 2020 Thursday
#Creating 1Dimensional Array (1D Array)
import numpy as np 
arr=np.array([10.0,20.0,30.0])
print(arr)
arr.ndim #it tells whether it is 1D or 2D array
arr.shape #it tells dimensions of array means number of rows and number of columns
arr.size #it tells number of values in array
arr.dtype #it tells about the data type of array elements
arr.itemsize #it tells element memory size of array elements in bits

[10. 20. 30.]


8

In [13]:
#Creating 2Dimensional Array (2D Array)
#2D OR MULTIDIMENSIONAL
import numpy as np 
arr=np.array([[10,20,30,40],[1,2,3,4],[15,25,35,45]])
print(arr)
arr.ndim #it tells whether it is 1D or 2D array
arr.shape #it tells dimensions of array means number of rows and number of columns
arr.size #it tells number of values in array
arr.dtype #it tells about the data type of array elements
arr.itemsize #it tells element memory size of array elements in bits

[[10 20 30 40]
 [ 1  2  3  4]
 [15 25 35 45]]


8

In [27]:
#CREATING ARRAYS OF DESIRED DATA TYPE
import numpy as np 
marks=np.array([10,20.12,30],dtype=int)
marks.dtype
marks
marks1=np.array([[10.50,20.75],[30.33,40.44]],dtype=float)
marks1.dtype
print(marks1)

[[10.5  20.75]
 [30.33 40.44]]


In [4]:
#October 16, 2020 Friday
#some NumPy functions to initialize arrays
#zeros(): It will array with 0 values
import numpy as np 
a=np.zeros((2,3))
print(a)
print(a.dtype)


[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [6]:
#ones(): it will initialize array with value 1
import numpy as np 
b=np.ones((10,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
arr=np.arange(1,5)
print(arr)
arr2=np.arange(1,15,5)
print(arr2)
arr3=np.arange(-10,10,3)
print(arr3)

[1 2 3 4]
[ 1  6 11]
[-10  -7  -4  -1   2   5   8]


In [24]:
#SLICING: It means extracting sub-set of values from an array/string/tuple/dictionary,dataframe,Series
values=np.arange(2,40,3)
a1=np.array(values)
print(a1) #it will print all values of array
print(a1[:]) #it will print all values of array
print(a1[:4]) #it will print all values till index 3
print(a1[::-1]) #it will print all values in reverse order
string="abcd"
print(string[::-1])
print(a1[5:10]) #it will print values from index 5 to index 9
print(a1[::2]) #it will print every 2nd value from array
print(a1[::3]) #it will print every 3rd value from array
print(a1[::-3]) #it will print every 3rd value from back side

[ 2  5  8 11 14 17 20 23 26 29 32 35 38]
[ 2  5  8 11 14 17 20 23 26 29 32 35 38]
[ 2  5  8 11]
[38 35 32 29 26 23 20 17 14 11  8  5  2]
dcba
[17 20 23 26 29]
[ 2  8 14 20 26 32 38]
[ 2 11 20 29 38]
[38 29 20 11  2]


In [38]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(a2) #all values will be printed
print() #blank line will be inserted
print(a2[:]) #all values of array will be printed
print() #blank line will be printed
print(a2[::2]) #it will display elements of every 2nd row
print()
print(a2[0:3]) #it will print all values of rows 0, 1, 2
print()
print(a2[1:2,1:2]) #it will print value of row1 col1
print()
print(a2[:,1:2]) #it will print column 1 values of all rows
print()
print(a2[1:3,0:3])
print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[7]]

[[ 2]
 [ 7]
 [12]
 [17]]

[[ 6  7  8]
 [11 12 13]]



In [10]:
#ARITHMETIC OPERATION ON ARRAYS
import numpy as np 
a1=np.array([[1,2],[3,4]])
a2=np.array([[4,6],[7,11]])
print(a1)
print()
print(a2)
print()
print("sum of matrices\n",a1+a2)
print()
print("Difference of matrices\n",a1-a2)
print()
print("Product of matrices\n",a1*a2)
print()
print("Product of matrices\n",a1@a2)
print()
print("Difference of matrices\n",a2-a1)
print()
print("Exponent of Matrix 1\n",a1)
print(a1**2)
print()
print("Matrix 1\n",a1)
print()
print("Matrix 2\n",a2)
print()
print("Quotient of Division\n",a2/a1)
print()
print("Remainder of Division\n",a2%a1)

[[1 2]
 [3 4]]

[[ 4  6]
 [ 7 11]]

sum of matrices
 [[ 5  8]
 [10 15]]

Difference of matrices
 [[-3 -4]
 [-4 -7]]

Product of matrices
 [[ 4 12]
 [21 44]]

Product of matrices
 [[18 28]
 [40 62]]

Difference of matrices
 [[3 4]
 [4 7]]

Exponent of Matrix 1
 [[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]

Matrix 1
 [[1 2]
 [3 4]]

Matrix 2
 [[ 4  6]
 [ 7 11]]

Quotient of Division
 [[4.         3.        ]
 [2.33333333 2.75      ]]

Remainder of Division
 [[0 0]
 [1 3]]


In [14]:
#TRANSPOSE OF MATRIX: it interchange row values in column and vice-versa
a1=np.array([[1,2],[3,4],[5,6]])
print(a1)
a2=a1.transpose()
#print("After Transpose of Matrix\n",a1.transpose())
print(a2)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [19]:
#SORTING: It means arranging the values of array in Ascending order
a3=np.array([5,1,3,10,7])
print(a3)
a3.sort()
print(a3)

[ 5  1  3 10  7]
[ 1  3  5  7 10]


In [2]:
#SORTING A 2D ARRAY
#NOTE: Elements of 2D are sorted ROW-WISE by deault
import numpy as np 
matrix=np.array([[6,4],[10,8],[1,12]])
print("Unsorted Sorted Array\n",matrix)
matrix.sort()
print("Sorted Array\n",matrix)

Unsorted Sorted Array
 [[ 6  4]
 [10  8]
 [ 1 12]]
Sorted Array
 [[ 4  6]
 [ 8 10]
 [ 1 12]]


In [3]:
#SORTING A 2D ARRAY COLUMN-WISE 
#NOTE: Elements of 2D are sorted ROW-WISE by deault
import numpy as np 
matrix=np.array([[6,4],[10,8],[1,12]])
print("Unsorted Sorted Array\n",matrix)
matrix.sort(axis=0)
print("Sorted Array\n",matrix)

Unsorted Sorted Array
 [[ 6  4]
 [10  8]
 [ 1 12]]
Sorted Array
 [[ 1  4]
 [ 6  8]
 [10 12]]


In [16]:
#CONCATENATING (JOINING/appending) ARRAY: It means joining to two or more array elements together in a resultant new array
#1D ARRAY
import numpy as np 
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("Array A\n",a)
print("Array B\n",b)
c=np.concatenate((b,a))
print("\nAFTER CONCATENATION")
print("Array C\n",c)

Array A
 [1 2 3 4]
Array B
 [5 6 7 8]

AFTER CONCATENATION
Array C
 [5 6 7 8 1 2 3 4]


In [22]:
#CONCATENATING 2D ARRAYS
import numpy as np 
matrix1=np.array([[1,2],[4,5],[6,7]])
matrix2=np.array([[10,11],[12,13],[14,15]])
print("MATRIX1\n",matrix1)
print("MATRIX2\n",matrix2)
matrix3=np.concatenate((matrix1,matrix2),axis=1)
print("CONCATENATED MATRIX3\n",matrix3)

MATRIX1
 [[1 2]
 [4 5]
 [6 7]]
MATRIX2
 [[10 11]
 [12 13]
 [14 15]]
CONCATENATED MATRIX3
 [[ 1  2 10 11]
 [ 4  5 12 13]
 [ 6  7 14 15]]


In [28]:
import numpy as np 
a=np.array([1,2,3,4])
matrix1=np.array([[1,2],[4,5],[6,7]])
print("Array 1\n",a)
print("Matrix1\n",matrix1)
print("RESHAPED\n")
print("Array 1\n",a.reshape(2,2))
print("Matrix1\n",matrix1.reshape(2,3))
print("Matrix1\n",matrix1.reshape(6))

Array 1
 [1 2 3 4]
Matrix1
 [[1 2]
 [4 5]
 [6 7]]
RESHAPED

Array 1
 [[1 2]
 [3 4]]
Matrix1
 [[1 2 4]
 [5 6 7]]
Matrix1
 [1 2 4 5 6 7]


In [27]:
#SPLIT(): It is used to split a matrix into number of sub array, the first will store first row, second will store next two rows, and third will store rest of the rows of the matrix

import numpy as np 
arr=np.array([[10,20,30],[40,50,60],[30,40,50],[11,12,13],[1,2,3],[6,7,8],[2,2,2]])
a1,a2,a3,a4,a5=np.split(arr,[1,3,4,5])
print()
print("Original Array\n",arr)
print()
print("Splitted Array a1\n",a1)
print()
print("Splitted Array a2\n",a2)
print()
print("Splitted Array a3\n",a3)
print()
print("Splitted Array a4\n",a4)
print()
print("Splitted Array a5\n",a5)


Original Array
 [[10 20 30]
 [40 50 60]
 [30 40 50]
 [11 12 13]
 [ 1  2  3]
 [ 6  7  8]
 [ 2  2  2]]

Splitted Array a1
 [[10 20 30]]

Splitted Array a2
 [[40 50 60]
 [30 40 50]]

Splitted Array a3
 [[11 12 13]]

Splitted Array a4
 [[1 2 3]]

Splitted Array a5
 [[6 7 8]
 [2 2 2]]


In [23]:
import numpy as np 
arr=np.array([[10,20,30],[40,50,60],[30,40,50],[11,12,13],[1,2,3],[6,7,8],[2,2,2]])
print("Original Matrix\n",arr)
#print("Through Slicing\n",arr[sr:er,sc:ec])
print("\nThrough Slicing\n",arr[:,:])
a1=arr[0:1,:]
print("\nSubset a1\n",a1)
a2=arr[1:3,:]
print("\nSubset a2\n",a2)
a3=arr[3:6,:]
print("\nSubset a3\n",a3)
a4=arr[6:,:]
print("\nSubset a4\n",a4)

Original Matrix
 [[10 20 30]
 [40 50 60]
 [30 40 50]
 [11 12 13]
 [ 1  2  3]
 [ 6  7  8]
 [ 2  2  2]]

Through Slicing
 [[10 20 30]
 [40 50 60]
 [30 40 50]
 [11 12 13]
 [ 1  2  3]
 [ 6  7  8]
 [ 2  2  2]]

Subset a1
 [[10 20 30]]

Subset a2
 [[40 50 60]
 [30 40 50]]

Subset a3
 [[11 12 13]
 [ 1  2  3]
 [ 6  7  8]]

Subset a4
 [[2 2 2]]


In [11]:
#STAISTICAL FUNCTIONS OF NUMPY USED FOR DATA ANALYSIS
import numpy as np 

a=np.array([-2,0,1,5,10,-5,7,6,-10,11])
b=np.array([[15,17,10,5],[7,20,18,12]])
print("The maximum value in array 1 ",a.max())
print("The maximum value in array 2",b.max())
print("The minimum value in array 1 ",a.min())
print("The minimum value in array 2 ",b.min())
print("Original Matrix\n",b)
print('The maximum value in array 2 on axis 0',b.max(axis=0))
print('The maximum value in array 2 on axis 1',b.max(axis=1))
print('The minimum value in array 2 on axis 0',b.min(axis=0))
print('The minimum value in array 2 on axis 1',b.min(axis=1))
bsum=b.sum()
print("Sum of 2D Elements",bsum)
a1sum=b.sum(axis=1)
print("Sum of 2D Elements on axis 1",bsum)
a0sum=b.sum(axis=0)
print("Sum of 2D Elements on axis 0",bsum)
m=b.mean()
print("mean of 2D Elements",m)
a1m=b.mean(axis=1)
print("Mean of 2D Elements on axis 1",a1m)
a0m=b.mean(axis=0)
print("Mean of 2D Elements on axis 0",a0m)
sd=b.std()
print("The Standard Deviation of Matrix/Array2 ",sd)
a1sd=b.std(axis=1)
print("The Standard Deviation of Matrix/Array2 on axis 1",a1sd)
a0sd=b.std(axis=0)
print("The Standard Deviation of Matrix/Array2 on axis 0",a0sd)

The maximum value in array 1  11
The maximum value in array 2 20
The minimum value in array 1  -10
The minimum value in array 2  5
Original Matrix
 [[15 17 10  5]
 [ 7 20 18 12]]
The maximum value in array 2 on axis 0 [15 20 18 12]
The maximum value in array 2 on axis 1 [17 20]
The minimum value in array 2 on axis 0 [ 7 17 10  5]
The minimum value in array 2 on axis 1 [5 7]
Sum of 2D Elements 104
Sum of 2D Elements on axis 1 104
Sum of 2D Elements on axis 0 104
mean of 2D Elements 13.0
Mean of 2D Elements on axis 1 [11.75 14.25]
Mean of 2D Elements on axis 0 [11.  18.5 14.   8.5]
The Standard Deviation of Matrix/Array2  5.049752469181039
The Standard Deviation of Matrix/Array2 on axis 1 [4.656984   5.11737237]
The Standard Deviation of Matrix/Array2 on axis 0 [4.  1.5 4.  3.5]


In [12]:
#October 26, 2020 Monday
#READING .CSV FILE DATA IN ARRAY
import numpy as np 
m=np.loadtxt("exam.csv",skiprows=1,delimiter=',',dtype=int)
print(m)

[[ 1 15 18 50]
 [ 2 18 15 25]
 [ 3 20 19 55]
 [ 4 12 13 56]
 [ 5 18 15 58]
 [ 6 17 16 52]
 [ 7 14 16 45]]


In [7]:
#unpack=True
#When argument=True is specified then values of columns of .CSV file can be stored in separate variables
import numpy as np 
r,u1,u2,h=np.loadtxt("exam.csv",skiprows=1,delimiter=',',dtype=int,unpack=True)
print("Roll Number = ",r)
print("UT1 Marks = ",u1)
print("UT2 Marks = ",u2)
print("Half-Yearly Marks = ",h)

Roll Number =  [1 2 3 4 5 6 7]
UT1 Marks =  [15 18 20 12 18 17 14]
UT2 Marks =  [18 15 19 13 15 16 16]
Half-Yearly Marks =  [50 25 55 56 58 52 45]


In [1]:
#genfromtxt() This function automatically handles missing values in .CSV fileexam.csv
import numpy as np 
m=np.genfromtxt("exam.csv",skip_header=1,delimiter=',',dtype=int)
print(m)

[[ 1 15 18 50]
 [ 2 18 15 25]
 [ 3 20 19 55]
 [ 4 12 13 56]
 [ 5 18 15 -1]
 [ 6 17 16 52]
 [ 7 14 16 45]]


In [6]:
#filling_values=value this argument of genfromtext() is used to specify the value in place missing elements of array in .CSV file
import numpy as np 
m=np.genfromtxt("exam.csv",skip_header=1,delimiter=',',dtype=int,filling_values=100)
print(m)
print(m*2)
mm=m*3
print(mm)

[[  1  15  18  50]
 [  2  18  15  25]
 [  3  20  19  55]
 [  4  12  13  56]
 [  5  18  15 100]
 [  6  17  16  52]
 [  7  14  16  45]]
[[  2  30  36 100]
 [  4  36  30  50]
 [  6  40  38 110]
 [  8  24  26 112]
 [ 10  36  30 200]
 [ 12  34  32 104]
 [ 14  28  32  90]]
[[  3  45  54 150]
 [  6  54  45  75]
 [  9  60  57 165]
 [ 12  36  39 168]
 [ 15  54  45 300]
 [ 18  51  48 156]
 [ 21  42  48 135]]


In [10]:
#savetext(destinationfile,sourcearray,delimiter,format) This function is used to store array values in text/.csv file
import numpy as np 
np.savetxt("output.txt",mm,delimiter=' ',fmt='%i')