In [6]:
import pandas as pd
data=[{'a':10, 'b':20},{'a':6,'b':32, 'c':22}]
df1=pd.DataFrame(data, index=["first","second"], columns=["a","b"])
df1.T

first  second
a     10       6
b     20      32

In [12]:
import pandas as jpd
a=[15,16,20]
b=[17,18,21]
d=[19,20,22]
myd={'A':a,'B':b,'C':d}
df=jpd.DataFrame(myd)
df

A   B   C
0  15  17  19
1  16  18  20
2  20  21  22

In [11]:
import numpy as knp
import pandas as jpd
a=[15,16,20]
b=[17,18,21]
d=[19,20,22]
myd={'A':a,'B':b,'D':d}
df=jpd.DataFrame(myd)
df['C']=knp.NaN
df

A   B   D   C
0  15  17  19 NaN
1  16  18  20 NaN
2  20  21  22 NaN

In [21]:
import pandas as jpd
import numpy as knp

a=[15,16,20]
b=[17,18,21]
d=[19,20,22]
myd={'A':a,'B':b,'D':d}
df=jpd.DataFrame(myd)
df['C']=[15,15,27]
df
df[['A','B','B']]

A   B   B
0  15  17  17
1  16  18  18
2  20  21  21

In [23]:
#pandas code to display minimum value from column 'A'
m=df['B'].min()
print(m)

17


In [2]:
import numpy as np                          
d=np.array([10,20,30,40,50,60,70])             
print(d[-4:])

[40 50 60 70]


In [1]:
import pandas as pd
sale=[5000, 60000,75000,25700, 65654]
person=['salman', 'ramesh', 'kannujia', 'dharmesh', 'pratap']
d={'salesmade':sale, 'salesman':person}
df=pd.DataFrame(d)
maxsales=df['salesmade'].max()
print(maxsales)
med=df['salesmade'].median()
print(med)


75000
60000.0


In [19]:
marks=[65,25,20,75,65,95,20]
m=100
for i in marks:
    if i<m:
        m=i
print(m) 


20


In [1]:
import numpy as np 
ar=np.arange(100,200,10)
print(ar)
print()
ar=ar.reshape(2,5)
print(ar)
print()
print(ar[:,4])
print(ar.shape)

[100 110 120 130 140 150 160 170 180 190]

[[100 110 120 130 140]
 [150 160 170 180 190]]

[140 190]
(2, 5)


In [1]:
import numpy as np 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
print(arr)
print()
print(np.amin(arr,0))
print()
print(np.amax(arr,1))
arr.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[3 6 9]


(3, 3)

In [19]:
import pandas as pd 
arr=np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
df=pd.DataFrame(arr)
df

0  1  2  3
0  1  2  3  0
1  4  5  6  0
2  7  8  9  0

In [18]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df=pd.DataFrame(arr)
df.cumsum()
#cumsum() is a function used to find sum of column values in a dataframe.

0   1   2
0   1   2   3
1   5   7   9
2  12  15  18

In [9]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df=pd.DataFrame(arr)
df.cummax()

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [11]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df=pd.DataFrame(arr)
df.cummin()

0  1  2
0  1  2  3
1  1  2  3
2  1  2  3

In [12]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df=pd.DataFrame(arr)
df.cumprod()

0   1    2
0   1   2    3
1   4  10   18
2  28  80  162

In [13]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df=pd.DataFrame(arr)
df.idxmax()

0    2
1    2
2    2
dtype: int64

In [14]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df=pd.DataFrame(arr)
df.idxmin()

0    0
1    0
2    0
dtype: int64

In [15]:
import pandas as pd 
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
df1=pd.DataFrame(arr)
df2=pd.DataFrame(arr)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [16]:
df2

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
df1+df2

0   1   2
0   2   4   6
1   8  10  12
2  14  16  18

In [ ]:
#MATCHING: It refers to default behaviour of data alignment on the basis of matching indexes is called MATCHING
#

In [19]:
import pandas as pd
import numpy as np 
ar=np.arange(50,100,2)   
v=pd.Series(ar)
v.count()   #count return number of values in array

25

In [2]:
import pandas as pd
import numpy as np 
ar=np.arange(50,100,2)   
v=pd.Series(ar)
v.hasnans   #hasnans return True either of element in array are Nan

False

In [3]:
ar>75

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
ar<75

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [4]:
ar*2

array([100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148,
       152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196])

In [7]:
ar**2

array([2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900,
       5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464,
       8836, 9216, 9604])

In [11]:
ar2=ar
print(ar2)
print()
print(ar)
print(ar+ar2)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]
[100 104 108 112 116 120 124 128 132 136 140 144 148 152 156 160 164 168
 172 176 180 184 188 192 196]


In [29]:
import numpy as np 
import pandas as pd 
ar=np.arange(10,60)
#df=pd.DataFrame(ar)
df=pd.DataFrame(ar,index=[x for x in range(60,10,-1)])
df


0
60  10
59  11
58  12
57  13
56  14
55  15
54  16
53  17
52  18
51  19
50  20
49  21
48  22
47  23
46  24
45  25
44  26
43  27
42  28
41  29
40  30
39  31
38  32
37  33
36  34
35  35
34  36
33  37
32  38
31  39
30  40
29  41
28  42
27  43
26  44
25  45
24  46
23  47
22  48
21  49
20  50
19  51
18  52
17  53
16  54
15  55
14  56
13  57
12  58
11  59

In [31]:
import numpy as np 
import pandas as pd 
ar=np.arange(1,12)
df=pd.DataFrame(ar,index=[x for x in "informatics"])
df
df2=df.reindex
df2

<bound method DataFrame.reindex of     0
i   1
n   2
f   3
o   4
r   5
m   6
a   7
t   8
i   9
c  10
s  11>

In [30]:
df2=df.reindex
df2

<bound method DataFrame.reindex of      0
60  10
59  11
58  12
57  13
56  14
55  15
54  16
53  17
52  18
51  19
50  20
49  21
48  22
47  23
46  24
45  25
44  26
43  27
42  28
41  29
40  30
39  31
38  32
37  33
36  34
35  35
34  36
33  37
32  38
31  39
30  40
29  41
28  42
27  43
26  44
25  45
24  46
23  47
22  48
21  49
20  50
19  51
18  52
17  53
16  54
15  55
14  56
13  57
12  58
11  59>

In [44]:

import numpy as np 
import pandas as pd 
ar1=np.arange(1,8)
df1=pd.DataFrame(ar1)
df1
ar2=np.arange(10,20)
df2=pd.DataFrame(ar2)
df2
df3=pd.concat([df1,df2],axis=1)
df3

0   0
0  1.0  10
1  2.0  11
2  3.0  12
3  4.0  13
4  5.0  14
5  6.0  15
6  7.0  16
7  NaN  17
8  NaN  18
9  NaN  19

In [7]:
import numpy as np 
import pandas as pd 
y1=[1000,2000,np.NaN,4000,5000]
y2=[2000,np.NaN,8000,10000,9000]
y3=[3000,6000,9000,4000,55000]
y4=[6000,9000,8000,2000,66000]
d1={'2019':y1, '2020':y2}
d2={'2019':y3,'2020':y4}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)
pd.concat([df1,df2],axis=1)

2019     2020   2019   2020
0  1000.0   2000.0   3000   6000
1  2000.0      NaN   6000   9000
2     NaN   8000.0   9000   8000
3  4000.0  10000.0   4000   2000
4  5000.0   9000.0  55000  66000

In [8]:
df1.combine_first(df2)

2019     2020
0  1000.0   2000.0
1  2000.0   9000.0
2  9000.0   8000.0
3  4000.0  10000.0
4  5000.0   9000.0

In [9]:
df2.combine_first(df1)

2019   2020
0   3000   6000
1   6000   9000
2   9000   8000
3   4000   2000
4  55000  66000

In [18]:
import numpy as np 
import pandas as pd 
r=[1,2,3,4,5]
fn=['ayush','ajay','kanha','pranshi','sanchit']
ln=['Maheshwari','kumar','narang','singla','singhal']
d1={'rno':r, 'fname':fn,'lname':ln}
#df1=pd.DataFrame([r,fn,ln])
df1=pd.DataFrame(d1)
df1

m=[15,18,11,14,17]
d2={'rno':r,'marks':m}
df2=pd.DataFrame(d2)
df2

pd.concat([df1,df2],axis=1)

#merge function to combine dataframes on common column.abs
pd.merge(df1,df2,on='rno')

rno    fname       lname  marks
0    1    ayush  Maheshwari     15
1    2     ajay       kumar     18
2    3    kanha      narang     11
3    4  pranshi      singla     14
4    5  sanchit     singhal     17

In [22]:
#wap to store name and marks in eng,ip,eco
#display name, eng, ip, eco, total marks, avg marks and grade
import pandas as pd 
nam=pd.Series(['rishita','sanchit','vaibhav','vansh','tisha'])
ip=pd.Series([95,75,79,70,80])
eg=pd.Series([80,75,70,65,80])
ec=pd.Series([78,70,70,65,80])
d={'name':nam, 'ip':ip,'eng':eg,'eco':ec}
df=pd.DataFrame(d)
print('Data Values in Dataframe')
df 
#now let's find tota marks,average marks and grade of each student
total=[]
grade=[]
avg=[]
for(row,rowSeries) in df.iterrows():
    tm=rowSeries['ip']+rowSeries['eng']+rowSeries['eco']
    total.append(tm)
    av=tm/3
    avg.append(av)
    if av>=91:
        grade.append('A+')
    elif av>=81 and av<=90:
        grade.append('A')
    elif av>=71 and av<=80:
        grade.append('B+')
    elif av>=61 and av<=70:
        grade.append('B')
    elif av>=51 and av<=60:
        grade.append('C')
    elif av>=41 and av<=50:
        grade.append('D')
    else:
        grade.append('E')

df['total']=total
df['average']=avg
df['grade']=grade

print('Now Data in DataFrame')
df

Data Values in Dataframe
Now Data in DataFrame


name  ip  eng  eco  total    average grade
0  rishita  95   80   78    253  84.333333     A
1  sanchit  75   75   70    220  73.333333    B+
2  vaibhav  79   70   70    219  73.000000    B+
3    vansh  70   65   65    200  66.666667     B
4    tisha  80   80   80    240  80.000000    B+